const API_CONST = {
  N_LOGIN_USER: 'N_LOGIN_USER',
  N_REGISTER_USER: 'N_REGISTER_USER',
  N_GET_FOOD_DETAILS_NUTRITION: 'N_GET_FOOD_DETAILS_NUTRITION',
  N_GET_FOOD_LIST_NUTRITION: 'N_GET_FOOD_LIST_NUTRITION',
  N_GET_PROFILE_DETAILS: 'N_GET_PROFILE_DETAILS',
  N_UPDATE_PROFILE_DETAILS: 'N_UPDATE_PROFILE_DETAILS',
  N_CLEAR_PROFILE: 'N_CLEAR_PROFILE',
  N_GET_RECOMMEDE_CAL: 'N_GET_RECOMMEDE_CAL',
  N_GET_FOOD_BY_DATE: 'N_GET_FOOD_BY_DATE',
  N_GET_FOOD_RECENT: 'N_GET_FOOD_RECENT',
  N_GET_FOOD_FREQUENT: 'N_GET_FOOD_FREQUENT',
  N_SAVE_NUTRITION_FOOD_DETAILS: 'N_SAVE_NUTRITION_FOOD_DETAILS',
  N_DELETE_FOOD: 'N_DELETE_FOOD',
};
export default API_CONST;
